//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class Candidate : Person
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public Candidate()
        {
            this.CandidateTests = new HashSet<CandidateTest>();
        }
    
    	private string _studentnumber;
        public  string StudentNumber 
		{ 
			get
			{ 
				return _studentnumber; 
			} 
			set
			{
				_studentnumber = value;
				ObjectPropertyChanged("StudentNumber");
			}
		}
    
        public virtual ICollection<CandidateTest> CandidateTests { get; set; }
    }
}
