//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal abstract partial class CandidateTest
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public CandidateTest()
        {
            this.Answers = new HashSet<Answer>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private System.Guid _testinstanceid;
        public  System.Guid TestInstanceId 
		{ 
			get
			{ 
				return _testinstanceid; 
			} 
			set
			{
				_testinstanceid = value;
				ObjectPropertyChanged("TestInstanceId");
			}
		}
    	private System.Guid _candidateid;
        public  System.Guid CandidateId 
		{ 
			get
			{ 
				return _candidateid; 
			} 
			set
			{
				_candidateid = value;
				ObjectPropertyChanged("CandidateId");
			}
		}
    	private int _stateid;
        public  int StateId 
		{ 
			get
			{ 
				return _stateid; 
			} 
			set
			{
				_stateid = value;
				ObjectPropertyChanged("StateId");
			}
		}
    	private System.DateTime _datetime;
        public  System.DateTime DateTime 
		{ 
			get
			{ 
				return _datetime; 
			} 
			set
			{
				_datetime = value;
				ObjectPropertyChanged("DateTime");
			}
		}
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Candidate Candidate { get; set; }
        public virtual TestInstance TestInstance { get; set; }
    }
}
