//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class QuestionBank
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public QuestionBank()
        {
            this.Questions = new HashSet<Question>();
        }
    
    	private System.Guid _testviewerid;
        public  System.Guid TestViewerId 
		{ 
			get
			{ 
				return _testviewerid; 
			} 
			set
			{
				_testviewerid = value;
				ObjectPropertyChanged("TestViewerId");
			}
		}
    
        public virtual ICollection<Question> Questions { get; set; }
        public virtual TestViewer TestViewer { get; set; }
    }
}
