//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class Question
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public Question()
        {
            this.Choices = new HashSet<Choice>();
            this.TestTemplates = new HashSet<TestTemplate>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private System.Guid _questionbankid;
        public  System.Guid QuestionBankId 
		{ 
			get
			{ 
				return _questionbankid; 
			} 
			set
			{
				_questionbankid = value;
				ObjectPropertyChanged("QuestionBankId");
			}
		}
    	private string _text;
        public  string Text 
		{ 
			get
			{ 
				return _text; 
			} 
			set
			{
				_text = value;
				ObjectPropertyChanged("Text");
			}
		}
    	private bool _active;
        public  bool Active 
		{ 
			get
			{ 
				return _active; 
			} 
			set
			{
				_active = value;
				ObjectPropertyChanged("Active");
			}
		}
    
        public virtual ICollection<Choice> Choices { get; set; }
        public virtual QuestionBank QuestionBank { get; set; }
        public virtual ICollection<TestTemplate> TestTemplates { get; set; }
    }
}
