
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain
{

using System;
    using System.Collections.Generic;
    
using System.ComponentModel;
internal partial class TestInstance
{
	

	partial void ObjectPropertyChanged(string propertyName);


    public TestInstance()
    {

        this.CandidateTests = new HashSet<CandidateTest>();

    }


	private System.Guid _id;
    public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}

	private System.Guid _templateid;
    public  System.Guid TemplateId 
		{ 
			get
			{ 
				return _templateid; 
			} 
			set
			{
				_templateid = value;
				ObjectPropertyChanged("TemplateId");
			}
		}

	private System.Guid _administeredby;
    public  System.Guid AdministeredBy 
		{ 
			get
			{ 
				return _administeredby; 
			} 
			set
			{
				_administeredby = value;
				ObjectPropertyChanged("AdministeredBy");
			}
		}

	private int _tokenid;
    public  int TokenId 
		{ 
			get
			{ 
				return _tokenid; 
			} 
			set
			{
				_tokenid = value;
				ObjectPropertyChanged("TokenId");
			}
		}

	private bool _ispractice;
    public  bool IsPractice 
		{ 
			get
			{ 
				return _ispractice; 
			} 
			set
			{
				_ispractice = value;
				ObjectPropertyChanged("IsPractice");
			}
		}

	private int _timelimit;
    public  int TimeLimit 
		{ 
			get
			{ 
				return _timelimit; 
			} 
			set
			{
				_timelimit = value;
				ObjectPropertyChanged("TimeLimit");
			}
		}



    public virtual Administrator Administrator { get; set; }

    public virtual ICollection<CandidateTest> CandidateTests { get; set; }

    public virtual TestTemplate TestTemplate { get; set; }

}

}
