//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class TestViewer
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public TestViewer()
        {
            this.People = new HashSet<Person>();
            this.TestTemplates = new HashSet<TestTemplate>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private string _developedby;
        public  string DevelopedBy 
		{ 
			get
			{ 
				return _developedby; 
			} 
			set
			{
				_developedby = value;
				ObjectPropertyChanged("DevelopedBy");
			}
		}
    
        public virtual ICollection<Person> People { get; set; }
        public virtual QuestionBank QuestionBank { get; set; }
        public virtual ICollection<TestTemplate> TestTemplates { get; set; }
    }
}
