
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain
{

using System;
    using System.Collections.Generic;
    
using System.ComponentModel;
internal partial class User
{
	

	partial void ObjectPropertyChanged(string propertyName);


	private System.Guid _applicationid;
    public  System.Guid ApplicationId 
		{ 
			get
			{ 
				return _applicationid; 
			} 
			set
			{
				_applicationid = value;
				ObjectPropertyChanged("ApplicationId");
			}
		}

	private System.Guid _userid;
    public  System.Guid UserId 
		{ 
			get
			{ 
				return _userid; 
			} 
			set
			{
				_userid = value;
				ObjectPropertyChanged("UserId");
			}
		}

	private string _username;
    public  string UserName 
		{ 
			get
			{ 
				return _username; 
			} 
			set
			{
				_username = value;
				ObjectPropertyChanged("UserName");
			}
		}

	private bool _isanonymous;
    public  bool IsAnonymous 
		{ 
			get
			{ 
				return _isanonymous; 
			} 
			set
			{
				_isanonymous = value;
				ObjectPropertyChanged("IsAnonymous");
			}
		}

	private System.DateTime _lastactivitydate;
    public  System.DateTime LastActivityDate 
		{ 
			get
			{ 
				return _lastactivitydate; 
			} 
			set
			{
				_lastactivitydate = value;
				ObjectPropertyChanged("LastActivityDate");
			}
		}



    public virtual Administrator Administrator { get; set; }

}

}
